const DOG_BREEDS = [
  'Akita Inu',
  'American Bully',
  'American Staffordshire Terrier',
  'Basset Hound',
  'Beagle',
  'Beauceron',
  'Berger Allemand',
  'Berger Australien',
  'Berger Belge Malinois',
  'Berger Blanc Suisse',
  'Berger des Shetland',
  'Bichon Frisé',
  'Bichon Maltais',
  'Border Collie',
  'Boston Terrier',
  'Bouledogue Anglais',
  'Bouledogue Français',
  'Bouvier Bernois',
  'Bouvier des Flandres',
  'Boxer',
  'Braque Allemand',
  'Braque de Weimar',
  'Briard',
  'Bull Terrier',
  'Cairn Terrier',
  'Caniche',
  'Cane Corso',
  'Carlin',
  'Cavalier King Charles',
  'Chihuahua',
  'Chow-Chow',
  'Cocker Anglais',
  'Cocker Américain',
  'Colley',
  'Corgi (Pembroke)',
  'Corgi (Cardigan)',
  'Coton de Tuléar',
  'Dalmatien',
  'Dobermann',
  'Dogue Allemand',
  'Dogue Argentin',
  'Dogue de Bordeaux',
  'Épagneul Breton',
  'Épagneul Papillon',
  'Fox Terrier',
  'Golden Retriever',
  'Grand Caniche',
  'Greyhound',
  'Griffon Bruxellois',
  'Husky Sibérien',
  'Irish Setter',
  'Jack Russell Terrier',
  'Kangal',
  'Labrador Retriever',
  'Labradoodle',
  'Lévrier Afghan',
  'Lhassa Apso',
  'Loulou de Poméranie',
  'Malamute de l\'Alaska',
  'Mastiff',
  'Montagne des Pyrénées',
  'Petit Brabançon',
  'Pinscher Nain',
  'Pitbull',
  'Pointer Anglais',
  'Rottweiler',
  'Saint-Bernard',
  'Samoyède',
  'Schnauzer',
  'Schnauzer Géant',
  'Schnauzer Nain',
  'Setter Anglais',
  'Setter Irlandais',
  'Shar Pei',
  'Shiba Inu',
  'Shih Tzu',
  'Spitz Japonais',
  'Springer Anglais',
  'Staffordshire Bull Terrier',
  'Teckel',
  'Terre-Neuve',
  'Terrier Écossais',
  'Welsh Terrier',
  'West Highland White Terrier',
  'Whippet',
  'Yorkshire Terrier',
  'Croisé / Mélange',
  'Autre',
  'Je ne sais pas',
];

export default DOG_BREEDS;
